### ISSUE TITLE
[Suggestion] Allow xp rate of 0

### ISSUE THREAD

**Issue by Trystanosaurus** [azerothcore/mod-individual-xp#1]
I'm not sure if this is the right place but on my server I find it useful to be able to set xp rate to 0, for example for level 60 characters who want to explore level 60 content before moving on to the burning crusade content.

I've made that change to my version of this module by simply changing line 83 from "if (rate == 0 || rate > MaxRate)" to "if (rate > MaxRate)" and thought I'd make the suggestion here in case other people would want the same way to individually turn off xp.

**Comment by BarbzYHOOL** [comment]
Why not setting max player level to 60 instead?

**Comment by Trystanosaurus** [comment]
Just if you have more than one player on the server, then some might want to be doing level 61-80 content while others want to do only level 60 stuff, or if you have alts at different levels it allows you to toggle xp on and off for each character individually without having to restart the server.

**Comment by BarbzYHOOL** [comment]
?? but it's about individual xp module then? not the xp rate for ALL players

Also you can reload config without rebooting the server.

**Comment by Trystanosaurus** [comment]
That's right, it's for the individual xp module only, that's why I posted here. As I say in the title, it's just a suggestion, it's something I've found useful so there might be others who'd use it too.

Also I've tried using reload config for other things and sometimes it seems to work and other times it doesn't, that might just be me though.

**Comment by BarbzYHOOL** [comment]
Lol, sorry man, I thought I was talking in the AC repository (also cause Shin liked the message). That's the second time I got tricked (coming from the github dashboard)

**Comment by BarbzYHOOL** [comment]
Quickly added it 327d5ab6d6545d0caeff92c3cc054e6e519214a4

Thank you for idea and line reference :P
