### ISSUE TITLE
remove this or replace

### ISSUE THREAD

**Issue by milestorme** [azerothcore/mod-individual-xp#16]
https://github.com/azerothcore/mod-individual-xp/blob/ef1a0fe298ea4594f85a8ba052905bb40784052b/src/Individual_XP.cpp#L101

@wizzymore this is in the wrong place either redo this statement or remove it and the } at the same time to fix travis and build warning, thats all i did

and comment victim
```
/home/travis/build/azerothcore/azerothcore-wotlk/modules/mod-individual-xp/src/Individual_XP.cpp:85:52: fatal error: unused parameter 'victim' [-Wunused-parameter]
    void OnGiveXP(Player* p, uint32& amount, Unit* victim) override
                                                     ^
1 error generated.
```

**Comment by wizzymore** [comment]
Hi milestorme,

The handlers we're done wrong from the beginning, not only that was the problem with the commands on this module.
Please check the following PR for the complete fix of the module: https://github.com/azerothcore/mod-individual-xp/pull/15

I want to thank you for you contribution even if you closed the pull request.
Please for the next time use a PR at a time so it will be easier to understand so we can test the pull request easier and merge it faster.

**Comment by milestorme** [comment]
Yeah your right , Your a legend this is much better , thank you 🙏.
