### ISSUE TITLE
[suggestion] make the xp rate as a opinion of npc talk

### ISSUE THREAD

**Issue by betayi** [azerothcore/mod-individual-xp#22]
if the XP rate  was selected by npc talk and with item exchange or money cost. it should be more funny

**Comment by pangolp** [comment]
> if the XP rate was selected by npc talk and with item exchange or money cost. it should be more funny

I really don't know if what you are asking for can be adapted to this module, or if it can be used in another type of module. The good thing about hooks is that they allow to use them in the modules, and in this way, create different mechanics. But the one you mention, I don't know if it would be better to have it in another type of module, and leave this one as it is. But maybe I'm wrong.
