### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by Dude100** [azerothcore/mod-individual-xp#23]
https://pastebin.com/7Rd3gv7S

OS Debian 10 

Linux clients-pools 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by Err0r1** [comment]
Confirmed.

@UltraNix

**Comment by ghost** [comment]
@Err0r1 Done.
