### ISSUE TITLE
[Suggestion] Add others rates

### ISSUE THREAD

**Issue by swervx** [azerothcore/mod-individual-xp#31]
I know this is out of mod-individual xp but adding other configurable "rates" such as honor rate, arena rate, loot rate, reputation rate...

(sorry I use a translator)

**Comment by pangolp** [comment]
> I know this is out of mod-individual xp but adding other configurable "rates" such as honor rate, arena rate, loot rate, reputation rate...
> 
> (sorry I use a translator)

I think that for that, as you mentioned, the best thing would be to create another mod. In this mod, it is about working more than anything the experience rates, however, the rest of the rates, can be worked in another mod without any doubt.
