### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by dev-master21** [azerothcore/mod-individual-xp#9]
hello 
![image](https://user-images.githubusercontent.com/16816228/68196036-29c55200-ffe2-11e9-968b-bb8ec8a201be.png)

last rev azerothcore

**Comment by talamortis** [comment]
Please try the above fix :)

**Comment by BarbzYHOOL** [comment]
and tell us result @csgomvs

**Comment by csgomvs** [comment]
![image](https://user-images.githubusercontent.com/16816228/68334192-4bb6f580-0104-11ea-9f79-baed94bd591b.png)
@talamortis @BarbzYHOOL @

**Comment by dev-master21** [comment]
![image](https://user-images.githubusercontent.com/16816228/68339664-37c4c100-010f-11ea-9498-e180f433e510.png)

**Comment by talamortis** [comment]
you have not applied the update.

Merge it @BarbzYHOOL , its passed on travis.

**Comment by talamortis** [comment]
Merge it @BarbzYHOOL , its passed on travis.

**Comment by dev-master21** [comment]
i replaced:   - mv mod-duelreset azerothcore/modules
to:   - mv mod-individual-XP azerothcore/modules
on: .travis.yml

**Comment by talamortis** [comment]
no.

https://github.com/azerothcore/mod-individual-xp/pull/10/commits/15fb14a4643a92327f7229e65e725644b87411ab

**Comment by dev-master21** [comment]
![image](https://user-images.githubusercontent.com/16816228/68344301-e4f00700-0118-11ea-8955-22c28573445c.png)

**Comment by BarbzYHOOL** [comment]
@csgomvs add back the missing `}` (check here https://github.com/azerothcore/mod-individual-xp/pull/10/files )

**Comment by BarbzYHOOL** [comment]
Or remove the `}` like Talamortis did, not sure what you did csgomvs but check the pull request -__-

**Comment by Jaredsk74** [comment]
I had the same original issue. Followed the pull request with and without the  extra `} `Now I get this:
![Capture](https://user-images.githubusercontent.com/10522469/68523958-19d19a80-028e-11ea-90b4-38a58fe15b2e.PNG)

**Comment by BarbzYHOOL** [comment]
it seems to indicate that you have to remove that extra `}` as talamortis did :D


http://www.azerothcore.org/wiki/How-to-test-a-PR guys

**Comment by BarbzYHOOL** [comment]
fixed
